#接下來會應用底下的讀寫分離提高SQL效能,SOURCES為寫,REPLICAS為讀
ex SOURCES_HOST=127.0.0.1
ex SOURCES_=5432
ex SOURCES_USER=postgres
ex SOURCES_PASSWORD=
ex SOURCES_DATABASE=replicas_database
ex SOURCES_SSLMODE=disable

ex REPLICAS_HOST=127.0.0.1
ex REPLICAS_=5432
ex REPLICAS_USER=
ex REPLICAS_PASSWORD=
ex REPLICAS_DATABASE=
ex REPLICAS_SSLMODE=
air