set DB_REPLICAS=0
set SOURCES_HOST=163.18.42.223
set SOURCES_PORT=1433
set SOURCES_USER=ManuOrder
set SOURCES_PASSWORD=nkuste215
set SOURCES_DATABASE=XMLY5000
set SOURCES_SSLMODE=disable

echo %SOURCES_DATABASE%
air.exe -c .air.toml
